language: node_js
node_js:
  - '11'

sudo: false
dist: trusty

cache: npm

notifications:
  email: false
  slack:
    rooms:
      - secure: eDd6HKlv7rxP5NBOI+5g11ZJCWc9MqV0gK03+rvCRjTQuuOG6s46RfxzqbzEM+HSNOI+7aw71hf1/611GAO3Qday3Hqu38b2KfHyOCLsntRRbDRiAYUTjJClAwjNvHsSFcovWSPAmdF3t8utYm3ZFI6LQRIesDd0aN5eoLGb8n7RRP70SpaAMRFjpEXKPqt/WIck6+bhTBoTl27Hiiajc3GvKB7V+hCDHJg8J9ktTkbQY0d9Rcu00jRrDPfBLJD4gAemkcozZAsy27cimaBWELAWR3enWFH3Fvvtl6aRG+lhQWA0R0zsgdZ3XUglZHRBYAY+cTV0kcehdwubBrHPF5KChawG+WbyASHcmmegcMi6uIq0pNQixwcbCIxx6gPasxiLHdKlva3KDw7fI3V5K5fmONX9CH6rjkXXyANVftCHxLyYdNkB26vmynSUClYPQLUTpAmurv/a9gMhMHjMVyspQ/WmzYOQComRz0Qr7MX04IoAtF8QfaonZOexFq77faqqN8/tT8zrVOfLtx4pYXFx1OpTWxbkKmqQCOOwMjkVTpNFjYzOlQ3F8JEYZmrCqoTiZ+18e16Xhi8bNeX/d4m9GQt6gzba9SEldkR9uXzWeMZ50PY1uW8QnaQL50NnRq1AfMSFGKXHvBM5llaEvX+kLJB8Rx4GYN1NrRaETwI=

branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run jest

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | $(npm bin)/coveralls